[2025-08-19T09:24:29.952+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T09:24:29.975+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_audit_dag.final_status_task scheduled__2025-08-19T08:00:00+00:00 [queued]>
[2025-08-19T09:24:29.985+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_audit_dag.final_status_task scheduled__2025-08-19T08:00:00+00:00 [queued]>
[2025-08-19T09:24:30.002+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-08-19T09:24:30.029+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): final_status_task> on 2025-08-19 08:00:00+00:00
[2025-08-19T09:24:30.040+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=141) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T09:24:30.043+0000] {standard_task_runner.py:63} INFO - Started process 146 to run task
[2025-08-19T09:24:30.043+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'data_audit_dag', 'final_status_task', 'scheduled__2025-08-19T08:00:00+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/Airflow Coding Assessment 2/data_audit_dag.py', '--cfg-path', '/tmp/tmpyb7jh27h']
[2025-08-19T09:24:30.048+0000] {standard_task_runner.py:91} INFO - Job 31: Subtask final_status_task
[2025-08-19T09:24:30.108+0000] {task_command.py:426} INFO - Running <TaskInstance: data_audit_dag.final_status_task scheduled__2025-08-19T08:00:00+00:00 [running]> on host 6cacbbe28f9c
[2025-08-19T09:24:30.200+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='youremail@example.com' AIRFLOW_CTX_DAG_OWNER='Anbu Dharshini' AIRFLOW_CTX_DAG_ID='data_audit_dag' AIRFLOW_CTX_TASK_ID='final_status_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T08:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-08-19T08:00:00+00:00'
[2025-08-19T09:24:30.202+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T09:24:30.204+0000] {logging_mixin.py:188} INFO - [Final]  Audit Success for user: 101
[2025-08-19T09:24:30.205+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-08-19T09:24:30.207+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T09:24:30.216+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=data_audit_dag, task_id=final_status_task, run_id=scheduled__2025-08-19T08:00:00+00:00, execution_date=20250819T080000, start_date=20250819T092429, end_date=20250819T092430
[2025-08-19T09:24:30.261+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-08-19T09:24:30.284+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-08-19T09:24:30.289+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
